### ISSUE TITLE
Userscript still opens in analysis page. Boxes still being used on the overlay to show positions.

### ISSUE THREAD

**Issue by botist** [FallDownTheSystem/ChessBotPy#8]
Pretty much the title. I downloaded your latest commit and updated the userscript to 7.0, but haven't noticed any changes. Just a heads up, I love your work!

**Comment by FallDownTheSystem** [comment]
It's still supposed to show boxes on the overlay. I'll probably make it draw arrows at some point. But which site is it still opening the UI on analysis pages?

Also I just made a new commit and a new release so maybe try those.

**Comment by botist** [comment]
Hi, I just downloaded your latest release and updated the userscript. The userscript is opening in the analysis page on chess.com still, sorry for not specifying that before.

**Comment by FallDownTheSystem** [comment]
It's not opening it for me on the analysis page on chess.com, can you link me a page where it opens?

**Comment by botist** [comment]
I've just tested and it's opening pretty much anytime I open a game to analyse or watch

**Comment by FallDownTheSystem** [comment]
It opens on the "watching" page because it's a live game (even though its over) and that's intended, but the analysis page is fine for me.

It's looking for the 'with_analysis' class on the body tag on that page, so if that's missing for you for some reason, then it would also open on the analysis page.

**Comment by botist** [comment]
Weird stuff, thanks for your input
